### ISSUE TITLE
Question : How can I use this to do class scheduling

### ISSUE THREAD

**Issue by kevindaus** [Pudge601/php-ga-lib#1]
Ive read on the internet that this algorithm can solve class scheduling  .I wonder if you can give us a sample usage / example code on how to use this library to accomplish that

**Comment by Pudge601** [comment]
Hi Kevin,

Thanks for the interest :)

As an initial disclaimer, I'll say that this library probably isn't a particularly good example of a generic algorithm library, I really just wrote it for my own academic curiosity, but haven't ever found a practical use for it myself.

I'm also by no means any kind of authority on genetic algorithms (or machine learning in general)!

With that said, I think the question about trying to solve a problem of "class scheduling" a perhaps a little too vague; that could describe a number of scenarios, so the problem would need to be more specically described before I could give an example of how to solve it.

What I will say is that if you do want to try and solve a problem by implementing a genetic algorithm, I think I'd recommend not using a library at all, as you would probably be better off trying to implement one specifically for the problem you want to solve. The reason for this is that the solution you would have to write would likely end up quite bespoke to the problem, as there are a lot of factors that determine how a genetic algorithm is implemented, for example;

- What is the "chromosome" (what does a candidate solution look like)?
- How do you rate the "fitness" of each chromosome (how close a solution is to being ideal/correct)?
- How will you "mutate" a chromosome (modify a chromosome to introduce some entropy in each generation)?
- How will you "crossover" two (or more) chromosomes (combine chromosomes to give new entries for the next generation)?

There's only so much a library like this can do to try and build an abstraction around those big variables, so it would probably just get in the way more than anything for any non-trivial problem.

Hope that helps! If you want more information on implementing genetic algorithms, it might be worth checking out some videos from either Code Bullet or The Coding Train on youtube, they explain things with some interesting examples.
